### ISSUE TITLE
dumpdata 'file' object has no attribute 'chunks'

### ISSUE THREAD

**Issue by cy-goh** [duncaningram/django-fixture-media#9]
trying to loaddata gives me the following error:

```
Traceback (most recent call last):
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/django/core/management/base.py", line 222, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(*args, **options)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/fixturemedia/management/commands/loaddata.py", line 51, in handle
    return super(Command, self).handle(*fixture_labels, **options)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 193, in handle
    obj.save(using=using)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/django/core/serializers/base.py", line 165, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/django/db/models/base.py", line 570, in save_base
    update_fields=update_fields)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 170, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/fixturemedia/management/commands/loaddata.py", line 36, in load_images_for_signal
    default_storage.save(path.name, f)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/django/core/files/storage.py", line 48, in save
    name = self._save(name, content)
  File "/Users/carrier24sg/.virtualenvs/pastacard/lib/python2.7/site-packages/django/core/files/storage.py", line 202, in _save
    for chunk in content.chunks():
AttributeError: Problem installing fixture 'pastacard/fixtures/mediadump.json': 'file' object has no attribute 'chunks'
```

**Comment by cy-goh** [comment]
I believe it should be default_storage.save(path.name, open(django.core.files.File(f)))
